library(openxlsx2)
library(pivottabler)

wb <- wb_workbook(creator = Sys.getenv("USERNAME"))
# wb$add_worksheet("bhmtrains", visible="hidden")
# wb$add_data(x=bhmtrains)
# pvt <- wb_data(wb)

# 1:  special case
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$renderPivot()
wb$add_worksheet("Sc1")
wb$add_data(sheet="Sc1", x="Sc1 Empty", col_names=FALSE, row_names=FALSE, dims = openxlsx2::wb_dims(cols=1, rows=1))
pt$writeToExcelWorksheet(wb=wb, wsName="Sc1", topRowNumber=3, leftMostColumnNumber=2, applyStyles=TRUE, mapStylesFromCSS=TRUE)
pt$renderPivot()

# 2a:  single measure on columns
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$defineCalculation(calculationName="TotalTrains", summariseExpression="n()")
pt$renderPivot()
wb$add_worksheet("Sc2a")
wb$add_data(sheet="Sc2a", x="Sc2a Only 1 Measure", col_names=FALSE, row_names=FALSE, dims = openxlsx2::wb_dims(cols=1, rows=1))
pt$writeToExcelWorksheet(wb=wb, wsName="Sc2a", topRowNumber=3, leftMostColumnNumber=2, applyStyles=TRUE, mapStylesFromCSS=TRUE)
# wb$add_pivot_table(x = pvt, data = "TrainCategory", fun = "count")
pt$renderPivot()

# 2b:  three measures on columns
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$defineCalculation(calculationName="TotalTrains1", summariseExpression="n()")
pt$defineCalculation(calculationName="TotalTrains2", summariseExpression="n()")
pt$defineCalculation(calculationName="TotalTrains3", summariseExpression="n()")
pt$renderPivot()
wb$add_worksheet("Sc2b")
wb$add_data(sheet="Sc2b", x="Sc2b Only 3 Measures", col_names=FALSE, row_names=FALSE, dims = openxlsx2::wb_dims(cols=1, rows=1))
pt$writeToExcelWorksheet(wb=wb, wsName="Sc2b", topRowNumber=3, leftMostColumnNumber=2, applyStyles=TRUE, mapStylesFromCSS=TRUE)
pt$renderPivot()

# 2c:  single measure plus rows
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$addRowDataGroups("TOC")
pt$defineCalculation(calculationName="TotalTrains", summariseExpression="n()")
pt$renderPivot()
wb$add_worksheet("Sc2c")
wb$add_data(sheet="Sc2c", x="Sc2c Measure plus Rows", col_names=FALSE, row_names=FALSE, dims = openxlsx2::wb_dims(cols=1, rows=1))
pt$writeToExcelWorksheet(wb=wb, wsName="Sc2c", topRowNumber=3, leftMostColumnNumber=2, applyStyles=TRUE, mapStylesFromCSS=TRUE)
# wb$add_pivot_table(x = pvt, rows = "TOC", data = "TrainCategory", fun = "count")
pt$renderPivot()

# 2d:  single measure plus rows and columns
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$addColumnDataGroups("TrainCategory")
pt$addRowDataGroups("TOC")
pt$defineCalculation(calculationName="TotalTrains", summariseExpression="n()")
pt$renderPivot()
wb$add_worksheet("Sc2d")
wb$add_data(sheet="Sc2d", x="Sc2d Measure plus RowsXCols", col_names=FALSE, row_names=FALSE, dims = openxlsx2::wb_dims(cols=1, rows=1))
pt$writeToExcelWorksheet(wb=wb, wsName="Sc2d", topRowNumber=3, leftMostColumnNumber=2, applyStyles=TRUE, mapStylesFromCSS=TRUE)
# wb$add_pivot_table(x = pvt, rows = "TOC", cols = "TrainCategory", data = "TrainCategory", fun = "count")
pt$renderPivot()

# 2e:  single measure plus rows and 2 sets of columns
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$addColumnDataGroups("TrainCategory")
pt$addColumnDataGroups("PowerType")
pt$addRowDataGroups("TOC")
pt$defineCalculation(calculationName="TotalTrains", summariseExpression="n()")
pt$renderPivot()
wb$add_worksheet("Sc2e")
wb$add_data(sheet="Sc2e", x="Sc2e Measure plus RowsX2Cols", col_names=FALSE, row_names=FALSE, dims = openxlsx2::wb_dims(cols=1, rows=1))
pt$writeToExcelWorksheet(wb=wb, wsName="Sc2e", topRowNumber=3, leftMostColumnNumber=2, applyStyles=TRUE, mapStylesFromCSS=TRUE)
# wb$add_pivot_table(x = pvt, rows = "TOC", cols = c("TrainCategory", "PowerType"), data = "TrainCategory", fun = "count")
pt$renderPivot()

# 2f:  three measures plus rows and 2 sets of columns
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$addColumnDataGroups("TrainCategory")
pt$addColumnDataGroups("PowerType")
pt$addRowDataGroups("TOC")
pt$defineCalculation(calculationName="TotalTrains1", summariseExpression="n()")
pt$defineCalculation(calculationName="TotalTrains2", summariseExpression="n()")
pt$defineCalculation(calculationName="TotalTrains3", summariseExpression="n()")
pt$renderPivot()
wb$add_worksheet("Sc2f")
wb$add_data(sheet="Sc2f", x="Sc2f 3 Measures plus RowsX2Cols", col_names=FALSE, row_names=FALSE, dims = openxlsx2::wb_dims(cols=1, rows=1))
pt$writeToExcelWorksheet(wb=wb, wsName="Sc2f", topRowNumber=3, leftMostColumnNumber=2, applyStyles=TRUE, mapStylesFromCSS=TRUE)
pt$renderPivot()

# 3a:  single measure on rows
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$defineCalculation(calculationName="TotalTrains", summariseExpression="n()")
pt$addRowCalculationGroups()
pt$renderPivot()
wb$add_worksheet("Sc3a")
wb$add_data(sheet="Sc3a", x="Sc3a Only 1 Measure", col_names=FALSE, row_names=FALSE, dims = openxlsx2::wb_dims(cols=1, rows=1))
pt$writeToExcelWorksheet(wb=wb, wsName="Sc3a", topRowNumber=3, leftMostColumnNumber=2, applyStyles=TRUE, mapStylesFromCSS=TRUE)
pt$renderPivot()

# 3b:  three measures on rows
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$defineCalculation(calculationName="TotalTrains1", summariseExpression="n()")
pt$defineCalculation(calculationName="TotalTrains2", summariseExpression="n()")
pt$defineCalculation(calculationName="TotalTrains3", summariseExpression="n()")
pt$addRowCalculationGroups()
pt$renderPivot()
wb$add_worksheet("Sc3b")
wb$add_data(sheet="Sc3b", x="Sc3b Only 3 Measures", col_names=FALSE, row_names=FALSE, dims = openxlsx2::wb_dims(cols=1, rows=1))
pt$writeToExcelWorksheet(wb=wb, wsName="Sc3b", topRowNumber=3, leftMostColumnNumber=2, applyStyles=TRUE, mapStylesFromCSS=TRUE)
pt$renderPivot()

# 3c:  single measure plus columns
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$addColumnDataGroups("TrainCategory")
pt$defineCalculation(calculationName="TotalTrains", summariseExpression="n()")
pt$addRowCalculationGroups()
pt$renderPivot()
wb$add_worksheet("Sc3c")
wb$add_data(sheet="Sc3c", x="Sc3c Measure plus Rows", col_names=FALSE, row_names=FALSE, dims = openxlsx2::wb_dims(cols=1, rows=1))
pt$writeToExcelWorksheet(wb=wb, wsName="Sc3c", topRowNumber=3, leftMostColumnNumber=2, applyStyles=TRUE, mapStylesFromCSS=TRUE)
# wb$add_pivot_table(x = pvt, cols = c("TrainCategory"), data = "TrainCategory", fun = "count")
pt$renderPivot()

# 3d:  single measure plus rows and columns (produces identical output to 2d)
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$addColumnDataGroups("TrainCategory")
pt$addRowDataGroups("TOC")
pt$defineCalculation(calculationName="TotalTrains", summariseExpression="n()")
pt$addRowCalculationGroups()
pt$renderPivot()
wb$add_worksheet("Sc3d")
wb$add_data(sheet="Sc3d", x="Sc3d Measure plus RowsXCols (same output as Sc2d)", col_names=FALSE, row_names=FALSE, dims = openxlsx2::wb_dims(cols=1, rows=1))
pt$writeToExcelWorksheet(wb=wb, wsName="Sc3d", topRowNumber=3, leftMostColumnNumber=2, applyStyles=TRUE, mapStylesFromCSS=TRUE)
# wb$add_pivot_table(x = pvt, rows = "TOC", cols = c("TrainCategory"), data = "TrainCategory", fun = "count")
pt$renderPivot()

# 3e:  single measure plus rows and 2 sets of columns (produces identical output to 2e)
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$addColumnDataGroups("TrainCategory")
pt$addColumnDataGroups("PowerType")
pt$addRowDataGroups("TOC")
pt$defineCalculation(calculationName="TotalTrains", summariseExpression="n()")
pt$addRowCalculationGroups()
pt$renderPivot()
wb$add_worksheet("Sc3e")
wb$add_data(sheet="Sc3e", x="Sc3e Measure plus RowsX2Cols (same output as Sc2e)", col_names=FALSE, row_names=FALSE, dims = openxlsx2::wb_dims(cols=1, rows=1))
pt$writeToExcelWorksheet(wb=wb, wsName="Sc3e", topRowNumber=3, leftMostColumnNumber=2, applyStyles=TRUE, mapStylesFromCSS=TRUE)
# wb$add_pivot_table(x = pvt, rows = "TOC", cols = c("TrainCategory", "PowerType"), data = "TrainCategory", fun = "count")
pt$renderPivot()

# 3f:  three measures plus rows and 2 sets of columns
pt <- PivotTable$new()
pt$addData(bhmtrains)
pt$addColumnDataGroups("TrainCategory")
pt$addColumnDataGroups("PowerType")
pt$addRowDataGroups("TOC")
pt$defineCalculation(calculationName="TotalTrains1", summariseExpression="n()")
pt$defineCalculation(calculationName="TotalTrains2", summariseExpression="n()")
pt$defineCalculation(calculationName="TotalTrains3", summariseExpression="n()")
pt$addRowCalculationGroups()
pt$renderPivot()
wb$add_worksheet("Sc3f")
wb$add_data(sheet="Sc3f", x="Sc3f 3 Measures plus RowsX2Cols", col_names=FALSE, row_names=FALSE, dims = openxlsx2::wb_dims(cols=1, rows=1))
pt$writeToExcelWorksheet(wb=wb, wsName="Sc3f", topRowNumber=3, leftMostColumnNumber=2, applyStyles=TRUE, mapStylesFromCSS=TRUE)
pt$renderPivot()

# finished
if (interactive()) {
  wb$open()
} else {
  wb$save(file="C:\\Users\\Chris\\Desktop\\test-openxlsx-v2.xlsx", overwrite = TRUE)
}
